owner: Virtual-Customs-Development
repo: upptime
user-agent: Virtual-Customs-Development

sites:
  - name: Virtual Customs
    url: $WEBSITE_URL_ONE
    icon: $WEBSITE_ICON_URL_ONE
  # - name: Test Broken Site
  #   url: $TEST_WEBSITE_URL
    
status-website:
  theme: ocean
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from [GitHub](https://github.com/$OWNER/$REPO).
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
