owner: Virtual-Customs-Development
repo: upptime
user-agent: Virtual-Customs-Development

sites:
  - name: Virtual Customs Forums
    url: https://virtualcustoms.net/
  - name: Virtual Customs Facebook
    url: https://www.facebook.com/profile.php?id=100066888865859
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co/
  #   icon: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    
status-website:
  theme: ocean
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from GitHub.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Social
      href: /upptime/social.html
